### ISSUE TITLE
Issue with Github logo in Dark-mode

### ISSUE THREAD

**Issue by vermastra** [bench-routes/dashboard#29]
### Discription
On the main [website](https://bench-routes.netlify.app/) there is an issue with the github logo in dark-mode . Github logo is not visible in dark mode because of its black color.

#### In Light mode 
![Screenshot (24)](https://user-images.githubusercontent.com/78556885/132970724-ed152876-ed34-4ab9-a561-f4cb0557c6ba.png)

#### In Dark mode
![Screenshot (23)](https://user-images.githubusercontent.com/78556885/132970730-9848e0c2-1b27-4f4a-91b7-f72c9e90f40c.png)

One can clearly see the difference on the top in both the mode.

### Request
Please assign it to me, I will make it to look like this!!!
@Harkishen-Singh @muskankhedia 

![Screenshot (25)](https://user-images.githubusercontent.com/78556885/132970941-90f6f8c6-19b0-4acb-a04a-78e0cdb5f891.png)

**Comment by ruddi10** [comment]
@vermastra you opened the issue in the wrong repo checkout https://github.com/bench-routes/benchdocs and open the issue here, also you can mention under the issue that you are working on it and make a PR for the same

**Comment by vermastra** [comment]
@ruddi10 sorry for this😅

**Comment by aquibbaig** [comment]
Closing this!
