### ISSUE TITLE
Replace store with zustand

### ISSUE THREAD

**Issue by aquibbaig** [bench-routes/dashboard#30]
We use https://github.com/jamiebuilds/unstated-next to manage our stores, but this package has some issues with memoization, so we would like to switch to a simple redux implementation such as `zustand`

**Comment by ruddi10** [comment]
@aquibbaig  so our we now planning to have a single centralized store? As I remember currently we are having two main containers containing our data

**Comment by satyaarthchhabra** [comment]
hi @aquibbaig, I want to work on this issue .

**Comment by ruddi10** [comment]
@aquibbaig I think the project structure will change a bit too right we may need to discuss that

**Comment by aquibbaig** [comment]
@satyaarthchhabra are you working on this? else I'd like to take this up

**Comment by aquibbaig** [comment]
Assigning this to myself for priority, if you had made some progress feel free to make a PR
