### ISSUE TITLE
center fetch button 

### ISSUE THREAD

**Issue by satyaarthchhabra** [bench-routes/dashboard#31]
Hi , the fetch button is currently left aligned and i feel it would be better if it could be in center.
![Capture](https://user-images.githubusercontent.com/56510402/136269173-8ddee45e-45fc-47eb-9a06-cd5122ca4bc0.PNG)

expected 

![1Capture](https://user-images.githubusercontent.com/56510402/136269528-7e1c5b5f-610e-4a60-b19e-19711a067ca7.PNG)

**Comment by muskankhedia** [comment]
@ruddi10 @satyaarthchhabra We can align the Fetch button to centre.

**Comment by aquibbaig** [comment]
@Hitansh-Shah I think @satyaarthchhabra is working on this

**Comment by satyaarthchhabra** [comment]
hi @aquibbaig, I had resolved it on that day but was not able to make a pull request on the same day. please review and merge the same
