### ISSUE TITLE
consistent data pattern across all the page components

### ISSUE THREAD

**Issue by aquibbaig** [bench-routes/dashboard#37]
Based on our useFetch service, the data pattern needs to be consistent across all page components (this is definitely what we need for a more readable and efficient design), for example:
```
// top level
const {error, loading, data} = useFetch(url)

if (error) return <div className="errorStyles">{error.message}</div>

if (loading && !data) return <div className="loading"><Spinner /></div>

if (!data) return <div>No data for the request</div>

// finally, shows data if everything's alright
return <div>{data.data}</div>
```

**Comment by akshatgarg12** [comment]
Can i work on this issue?

**Comment by aquibbaig** [comment]
@akshatgarg12 Sure, let me know if you need any help :)

Referencing a dependency in this comment [#24](https://github.com/bench-routes/dashboard/issues/24)

**Comment by akshatgarg12** [comment]
@aquibbaig Shall i remove error as a prop from [RouteList](https://github.com/bench-routes/dashboard/blob/6faa0e13f87d6faaecc75ae2a563f55ee4b778c4/src/components/RouteList/index.tsx#L26) component, so that we can handle the error without passing it?

**Comment by aquibbaig** [comment]
yeah, I guess.
Errors should be handled in a scope where data is being fetched
