### ISSUE TITLE
Remove faker js and use another library

### ISSUE THREAD

**Issue by aquibbaig** [bench-routes/dashboard#43]
Because `What really happened with Aaron Swartz?`

**Comment by MohdImran001** [comment]
@aquibbaig can I work on it ?

**Comment by MohdImran001** [comment]
@aquibbaig  The whole faker repo has been deleted. 🙁

I found this thread in reddit - https://www.reddit.com/r/node/comments/rwp0ab/comment/hrdj5nr/

Meanwhile I m exploring new libraries that would be a good fit for bench-routes.
